export const ZEDBEE_COMMAND = "npx --no-install zedbee scan --hook-invocation";
const ZEDBEE_SCAN_COMMAND =
  /(?:^|[\n;&|])\s*(?:npx(?:\s+--no-install)?\s+)?(?:\.\/node_modules\/\.bin\/)?zedbee\s+scan(?:\s|$)/u;

export function hasZedbeeScanCommand(source: string): boolean {
  return (
    ZEDBEE_SCAN_COMMAND.test(source) ||
    /(?:^|[\n;&|])\s*node\s+['"][^\n]+\/node_modules\/zedbee\/[^\n]+['"]\s+scan(?:\s|$)/u.test(
      source,
    )
  );
}

/** Refresh only commands generated by Zedbee; preserve custom invocations. */
export function replaceManagedZedbeeCommand(
  source: string,
  command: string,
): string {
  if (command === ZEDBEE_COMMAND) return source;
  return source
    .split("\n")
    .map((line) =>
      line.trim() === ZEDBEE_COMMAND ||
      line.trim() === "npx --no-install zedbee scan" ||
      (line.startsWith("node '") &&
        line.endsWith(" scan --hook-invocation") &&
        hasZedbeeScanCommand(line)) ||
      (line.startsWith('(cd "$(git rev-parse --show-toplevel)" && node \'') &&
        line.endsWith(" scan --hook-invocation)") &&
        hasZedbeeScanCommand(line))
        ? command
        : line,
    )
    .join("\n");
}

export function updateHuskyHook(
  before: string | null | undefined,
  command = ZEDBEE_COMMAND,
): string {
  const source = replaceManagedZedbeeCommand(before ?? "#!/bin/sh\n", command);
  if (hasZedbeeScanCommand(source)) return source;
  const hadFinalNewline = source.endsWith("\n");
  const lines = source.split("\n");
  if (hadFinalNewline) lines.pop();
  let insertion = lines.length;
  while (insertion > 0 && lines[insertion - 1]?.trim() === "") insertion -= 1;
  if (/^exit(?:\s|$)/u.test(lines[insertion - 1]?.trim() ?? "")) {
    insertion -= 1;
  }
  lines.splice(insertion, 0, command);
  return `${lines.join("\n")}\n`;
}
