export const MAX_LOCKFILE_BYTES = 8 * 1024 * 1024;
export const MAX_DEPENDENCY_RECORDS = 10_000;
export const MAX_LOCKFILE_NESTING = 128;
export const MAX_LOCKFILE_NODES = 100_000;
export const MAX_LOCKFILE_STRING_LENGTH = 8_192;
export const MAX_PACKAGE_NAME_LENGTH = 214;
export const MAX_PACKAGE_VERSION_LENGTH = 256;
export const MAX_DEPENDENCY_PATH_LENGTH = 128;
